require_relative '../node_modules/react-native-test-app/test_app'

use_flipper!({
               'Flipper' => '0.75.1',
               'Flipper-Folly' => '2.5.3',
               'Flipper-RSocket' => '1.3.1',
             })

workspace 'MenuExample.xcworkspace'

use_test_app!
